### ISSUE TITLE
loader prototype

### ISSUE THREAD

**Issue by niquola** [fhirbase/fhirbase#1]
We need support for:

* [x] resource by file or url
* [x] bundle by file or url
* [x] bulk api
* [x] synthea
* [x] FHIR examples zip

Guys push your experiments into master - do CI

**Comment by niquola** [comment]
We need support for:

* resource by file or url
* bundle by file or url
* bulk api
* synthea
* FHIR examples zip

**Comment by ruscoder** [comment]
Now we have
1. aidboxconv module (http://github.com/ruscoder/aidboxconv) which converts ndjson (FHIR -> Aidbox compatible) from stdin into entry "id, txid, resource type, transformed ndjson". 
2. python util (WIP) which accepts different types of input

Python util receives multiple files (json, ndjson, zip with json, ndjson) and passes them into pipe for aidboxconv.jar, and after that passes the transformed result into psql COPY.

For 1600000(1.4GB) resources on my Mac we reached 3500 resources per second (~7min).
Without convertion on fly by aidboxconv it takes ~5.5min.

TODO:
* [x] Load data from Synthea
* [x] Load data from Bulk api
* [x] Use postgres module instead of Popen() for executing COPY and other commands
* [x] Create trigger and temporary table before import
* [ ] Install aidboxconv (should be discussed)
